import { EventEmitter, OnDestroy } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { ExpressionTextareaComponent } from './expression-textarea/expression-textarea.component';
import { ExpressionEvaluatorService } from '../../services/expression-evaluator/expression-evaluator.service';
import { ExtensionManagerService } from '../../services/extension-manager/extension-manager.service';
import { CustomFunction } from '../../interfaces/core/extensibility.interfaces';
import { FunctionCategory, FunctionItem, SymbolCategory, SymbolItem, ExpressionEditorConfig, TypeValidationResult, Variable, ExpressionResult, ExpressionEditorConfigEnhanced, BinaryTreeResult, TextareaStyleConfig, FieldMappingData } from '../../interfaces/shared.interfaces';
import * as i0 from "@angular/core";
export declare class ExpressionEditorComponent implements ControlValueAccessor, OnDestroy {
    private evaluatorService;
    private extensionManager;
    disabled: boolean;
    editorConfig?: ExpressionEditorConfig | ExpressionEditorConfigEnhanced;
    simpleMode: boolean;
    textareaStyle?: TextareaStyleConfig;
    placeholder?: string;
    expressionChange: EventEmitter<string>;
    validationChange: EventEmitter<TypeValidationResult | null>;
    configChange: EventEmitter<ExpressionEditorConfig | ExpressionEditorConfigEnhanced>;
    binaryTreeChange: EventEmitter<BinaryTreeResult | null>;
    fieldMappingChange: EventEmitter<FieldMappingData | null>;
    expressionTextarea: ExpressionTextareaComponent;
    value: string;
    typeResult: ExpressionResult | null;
    currentValidation: TypeValidationResult | null;
    showFunctionsMenu: boolean;
    showSymbolPicker: boolean;
    showCustomFunctionBuilder: boolean;
    showVariableManager: boolean;
    selectedFunction: FunctionItem | null;
    selectedSymbol: SymbolItem | null;
    selectedFunctionCategory: string;
    selectedSymbolCategory: string;
    private onChange;
    private onTouched;
    private debounceTimer;
    private debounceDelay;
    functionCategories: FunctionCategory[];
    symbolCategories: SymbolCategory[];
    constructor(evaluatorService: ExpressionEvaluatorService, extensionManager: ExtensionManagerService);
    private initializeFunctionCategories;
    get enhancedConfig(): ExpressionEditorConfigEnhanced | undefined;
    get variables(): Variable[];
    onValueChange(value: string): void;
    onTextareaBlur(): void;
    onToggleEditor(): void;
    onClearExpression(): void;
    onConfigChange(newConfig: ExpressionEditorConfig | ExpressionEditorConfigEnhanced): void;
    onOpenFunctionsMenu(): void;
    onCloseFunctionsMenu(): void;
    onFunctionCategorySelected(category: string): void;
    onFunctionSelected(func: FunctionItem): void;
    onFunctionInserted(func: FunctionItem): void;
    onOpenSymbolPicker(): void;
    onCloseSymbolPicker(): void;
    onSymbolCategorySelected(category: string): void;
    onSymbolSelected(symbol: SymbolItem): void;
    onSymbolInserted(symbol: SymbolItem): void;
    onOpenCustomFunctionBuilder(): void;
    onCloseCustomFunctionBuilder(): void;
    onCustomFunctionCreated(customFunction: CustomFunction): void;
    onOpenVariableManager(): void;
    onCloseVariableManager(): void;
    onVariableSelected(variable: Variable): void;
    onVariableInserted(variable: Variable): void;
    onVariableCreated(variable: Variable): void;
    onVariableDeleted(variable: Variable): void;
    insertTextAtCursor(text: string): void;
    analyzeExpression(): void;
    writeValue(value: string | null): void;
    registerOnChange(fn: (value: string) => void): void;
    registerOnTouched(fn: () => void): void;
    setDisabledState(isDisabled: boolean): void;
    getTextareaStyles(): any;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ExpressionEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ExpressionEditorComponent, "lib-expression-editor", never, { "disabled": { "alias": "disabled"; "required": false; }; "editorConfig": { "alias": "editorConfig"; "required": false; }; "simpleMode": { "alias": "simpleMode"; "required": false; }; "textareaStyle": { "alias": "textareaStyle"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; }, { "expressionChange": "expressionChange"; "validationChange": "validationChange"; "configChange": "configChange"; "binaryTreeChange": "binaryTreeChange"; "fieldMappingChange": "fieldMappingChange"; }, never, never, true, never>;
}
